#version 460 core
layout (local_size_x =    , local_size_y =    , local_size_z =    ) in;
layout(rgba32f, binding = 1) writeonly restrict uniform image2D imageOut;




void main()
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    vec4 value = vec4(
        float(texelCoord.x)/(gl_NumWorkGroups.x),
        float(texelCoord.y)/(gl_NumWorkGroups.y),
        0.0f,
        1.0f
    );

    imageStore(imageOut, texelCoord, vec4(1.0f, 1.0f, 0.0f, 1.0f));
}
